//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipes {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recipes.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИЗМЕНИТЬ.
        /// </summary>
        public static string AddButtonChange {
            get {
                return ResourceManager.GetString("AddButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УДАЛИТЬ.
        /// </summary>
        public static string AddButtonDelete {
            get {
                return ResourceManager.GetString("AddButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВИТЬ ИЗОБРАЖЕНИЕ.
        /// </summary>
        public static string AddButtonImage {
            get {
                return ResourceManager.GetString("AddButtonImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название рецепта.
        /// </summary>
        public static string AddEditName {
            get {
                return ResourceManager.GetString("AddEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите время приготовления в минутах.
        /// </summary>
        public static string AddEditTime {
            get {
                return ResourceManager.GetString("AddEditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите шаг приготовления.
        /// </summary>
        public static string AddEntryPlaceholderInstruction {
            get {
                return ResourceManager.GetString("AddEntryPlaceholderInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление рецепта.
        /// </summary>
        public static string AddName {
            get {
                return ResourceManager.GetString("AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ингредиент.
        /// </summary>
        public static string AddPlaceholderIngred {
            get {
                return ResourceManager.GetString("AddPlaceholderIngred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ед..
        /// </summary>
        public static string AddPlaceholderUnit {
            get {
                return ResourceManager.GetString("AddPlaceholderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string AddPlaceholderWeight {
            get {
                return ResourceManager.GetString("AddPlaceholderWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВИТЬ РЕЦЕПТ.
        /// </summary>
        public static string AddRecipe {
            get {
                return ResourceManager.GetString("AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВИТЬ ШАГ.
        /// </summary>
        public static string AddStep {
            get {
                return ResourceManager.GetString("AddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип блюда: .
        /// </summary>
        public static string AddTypeDish {
            get {
                return ResourceManager.GetString("AddTypeDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все рецепты.
        /// </summary>
        public static string CatalogAllRecipes {
            get {
                return ResourceManager.GetString("CatalogAllRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог Рецептов.
        /// </summary>
        public static string CatalogNamePage {
            get {
                return ResourceManager.GetString("CatalogNamePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск....
        /// </summary>
        public static string CtalogSearch {
            get {
                return ResourceManager.GetString("CtalogSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВИТЬ РЕЦЕПТ.
        /// </summary>
        public static string DetailAddRecipe {
            get {
                return ResourceManager.GetString("DetailAddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КАТАЛОГ.
        /// </summary>
        public static string DetailCatalog {
            get {
                return ResourceManager.GetString("DetailCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОИСК ПО ИНГРЕДИЕНТАМ.
        /// </summary>
        public static string DetailSearch {
            get {
                return ResourceManager.GetString("DetailSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАСТРОЙКИ.
        /// </summary>
        public static string DetailSetting {
            get {
                return ResourceManager.GetString("DetailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели имя ингредиента.
        /// </summary>
        public static string ErrorIngred {
            get {
                return ResourceManager.GetString("ErrorIngred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели название рецепта.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не добавили ни одного ингредиента.
        /// </summary>
        public static string ErrorNullIngred {
            get {
                return ResourceManager.GetString("ErrorNullIngred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не добавили ни одного шага приготовления.
        /// </summary>
        public static string ErrorNullStep {
            get {
                return ResourceManager.GetString("ErrorNullStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите шаг.
        /// </summary>
        public static string ErrorStep {
            get {
                return ResourceManager.GetString("ErrorStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели примерное время приготовления.
        /// </summary>
        public static string ErrorTime {
            get {
                return ResourceManager.GetString("ErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество должно содержать только числа.
        /// </summary>
        public static string ErrorWeight {
            get {
                return ResourceManager.GetString("ErrorWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ккал.
        /// </summary>
        public static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мин..
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ок.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в избранное.
        /// </summary>
        public static string PageAddFavorite {
            get {
                return ResourceManager.GetString("PageAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убрать из избранных.
        /// </summary>
        public static string PageDelFavorite {
            get {
                return ResourceManager.GetString("PageDelFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип блюда.
        /// </summary>
        public static string TypeDish {
            get {
                return ResourceManager.GetString("TypeDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завтрак.
        /// </summary>
        public static string TypeDishBreakfast {
            get {
                return ResourceManager.GetString("TypeDishBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string TypeDishCencal {
            get {
                return ResourceManager.GetString("TypeDishCencal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напиток.
        /// </summary>
        public static string TypeDishDrink {
            get {
                return ResourceManager.GetString("TypeDishDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первое блюдо.
        /// </summary>
        public static string TypeDishFirst {
            get {
                return ResourceManager.GetString("TypeDishFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        public static string TypeDishOther {
            get {
                return ResourceManager.GetString("TypeDishOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Салат.
        /// </summary>
        public static string TypeDishSalad {
            get {
                return ResourceManager.GetString("TypeDishSalad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Второе блюдо.
        /// </summary>
        public static string TypeDishSecond {
            get {
                return ResourceManager.GetString("TypeDishSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Избранные.
        /// </summary>
        public static string СatalogFavorite {
            get {
                return ResourceManager.GetString("СatalogFavorite", resourceCulture);
            }
        }
    }
}
